# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e54aeced3ebccf544d62d493e8d30dbbca0bc09b8a16a911d895aa44acd9af53dfc212171f269e4a129fa233ce77161244ea4d9a70914e060ffef8d3692ebd92

test:
  secret_key_base: dc9ec245efbf9f32c47e48c66a282334134e2ed9b74f1b78fa89e4c08f244a4d6c4b1c5f0e7b0712e23da369bfda6566055a12aa1b8f5388e483c814a78f9c91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
